### ISSUE TITLE
Unexpected Reference error : Jquery is not defined , $ fullClip is not a function

### ISSUE THREAD

**Issue by lowzijian** [bdimitrovski/full_clip#3]
I developed the same thing and put it in my current laravel project. Could i know what kind of script i need to import , other than fullclip and fullclip.min
![image](https://user-images.githubusercontent.com/40559529/55246896-3c73ed80-5281-11e9-9838-f784953d410e.png)

**Comment by bdimitrovski** [comment]
Hey @lowzijian, you will need to include jQuery beforehand, as this script has a dependency on it. Something like

```
<head>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
<script src="/js/fullclip.min.js"></script>
</head>
```

**Comment by lowzijian** [comment]
@bdimitrovski  the problem was fixed. Thank You.
